Notebook to quick test my masked conv implementation

In [24]:
import pixelrnn.models as models
import torch

In [26]:
mconv = models.MaskedConv2d(3, 15, kernel_size=7)
print(mconv)

MaskedConv2d(3, 15, kernel_size=(7, 7), stride=(1, 1))


In [27]:
mconv.mask.shape

torch.Size([15, 3, 7, 7])

Each input channel has associated 5 output channels, which will be used to predict the color values in the final stage

here 15 is the value of _h_ in the paper.

therefore, the first 5 output channels should only focus on the context, the next 5 channels shouild focus on the contexts
plus the firs in channel (red) and the last 5 channels should see the first and second channel (red, green) but not the last (blue)

notice the central value of the kernel

In [28]:
mconv.mask[0]

tensor([[[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]]])

In [29]:
mconv.mask[5]

tensor([[[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]]])

In [30]:
mconv.mask[10]

tensor([[[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]]])

In [31]:
mconv.weight[0]

tensor([[[-0.0042,  0.0086,  0.0807, -0.0547,  0.0423,  0.0388,  0.0542],
         [ 0.0123,  0.0490,  0.0398,  0.0222, -0.0386,  0.0685, -0.0526],
         [ 0.0064,  0.0280,  0.0002,  0.0228, -0.0266, -0.0634, -0.0073],
         [ 0.0585, -0.0417, -0.0669, -0.0000, -0.0000, -0.0000, -0.0000],
         [-0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000],
         [-0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000, -0.0000],
         [-0.0000, -0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000]],

        [[ 0.0302,  0.0322, -0.0413, -0.0755,  0.0048, -0.0168,  0.0444],
         [-0.0567, -0.0455, -0.0377,  0.0726,  0.0491,  0.0387,  0.0052],
         [-0.0450, -0.0515, -0.0083, -0.0762,  0.0587,  0.0738, -0.0713],
         [ 0.0368, -0.0111, -0.0277, -0.0000, -0.0000, -0.0000, -0.0000],
         [ 0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000,  0.0000],
         [ 0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.0000, -0.0000, -0.0000,

In [32]:
mconv.weight.requires_grad

True

In [33]:
mconv.weight.grad == None and mconv.weight.grad_fn == None

True

In [34]:
out = mconv(torch.rand(3, 16, 16))

In [35]:
print(out.shape)

torch.Size([15, 10, 10])


In [36]:
loss = out.sum()
loss.backward()

In [42]:
mconv.weight.grad[0]

tensor([[[52.3064, 52.2874, 53.2236, 54.3701, 52.2719, 51.0724, 52.2985],
         [52.8811, 52.0356, 53.7780, 54.5993, 52.5928, 52.7514, 54.8170],
         [54.1581, 53.0805, 54.7686, 55.3726, 54.5265, 54.8130, 56.0861],
         [55.6373, 53.0983, 53.5719,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[50.5509, 49.4235, 49.0846, 49.9353, 49.0742, 48.6609, 49.4021],
         [51.5525, 50.6719, 50.5354, 50.9387, 50.9939, 50.3543, 50.6520],
         [50.4905, 48.9948, 48.4662, 49.2351, 49.1483, 48.6829, 48.8978],
         [50.9918, 50.9123, 50.2490,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,

test single channel images

In [43]:
mconv = models.MaskedConv2d(1, 8, kernel_size=7)

In [44]:
mconv.weight.shape

torch.Size([8, 1, 7, 7])

In [48]:
out = mconv(torch.rand(1, 16, 16))
out.shape

torch.Size([8, 10, 10])

In [54]:
mconv.weight.shape == mconv.mask.shape

True